### ISSUE TITLE
Support and story typo

### ISSUE THREAD

**Issue by jftm999** [TeamIf/FireEmblemIf-FanTranslation#1]
1-Orochi and Ryouma c support (change he to she when mentioning Kagerou)

2-Takumi and Oboro C support missing

3- ch 12 after battle, missing dialog between MC and Takumi

**Comment by galaxygamr98** [comment]
1- Fixed.
2- Fixed.
3- Could you please specify which chapter 12 you mean? Hoshido, Nohr, or Invisible Kingdom?

**Comment by ShadySheikah** [comment]
Looked through the three routes and found a blank page in the Hoshido chapter. For whatever reason, that page's text was present in one version of the conversation but missing from the others.
