### ISSUE TITLE
IK chapter 27 - epilogue and a blank skinship box

### ISSUE THREAD

**Issue by ghost** [TeamIf/FireEmblemIf-FanTranslation#11]
during the confrontation with Hydra at the start Ryouma refers to female Kamui as "him"

> We will defend him with all our strength!

during the coronation for the avatar Aqua's line "...Kamui, as proof of your new enthronement" is forcibly skipped and continues on to the next dialogue box.

when Aqua and Kamui are at the lake there is a dialogue box that has two words not spaced properly.

> Butis this really okay???

I was playing as the female avatar for the above issues.

Finally, one of Tsubaki's romantic skinship lines is blank when it comes up.

**Comment by ShadySheikah** [comment]
We're still working on figuring out why some skinship lines show up as blank, but the issues with IK are fixed with 4.2.
