### ISSUE TITLE
Hoshido story and Support Typo

### ISSUE THREAD

**Issue by jftm999** [TeamIf/FireEmblemIf-FanTranslation#2]
Sorry for the last issue, I didn't specify which kingdom, currently, this is what I found for ( Hoshido version )after finishing the story: 
Story Typo:
1-Ch13 after battle missing dialog between MC and Takumi
2- Ch18 after battle, two lines not translated When MC talks to Leon
3- Prologue (Female Kana), there's a line says by the MC only says (Ce!) and it's colored violet on the opening scene when MC saves the daughter
4- Prologue Sophie, Missing the whole dialog after battle

Support Typo:
1- Takumi and Oboro C support missing
2- Joker and Sakurai B support missing
3- Joker and Hinoka A support First line not translated
4- MC and Matoi C support, the Phrase (Though I can understand his feelings of ....) is repeated
5- MC and Syalla C,B,A Supports, MC calls her Shara instead of Syalla, not sure about S support

**Comment by galaxygamr98** [comment]
All support typos have been fixed. We just have to wait for the repo to update next month with the fixes. Story typos on the other hand, are not my forte. I'll leave those to someone more experienced at editing them.
