### ISSUE TITLE
Hoshido Female No.3 Mistakes

### ISSUE THREAD

**Issue by AnyaByakuya** [TeamIf/FireEmblemIf-FanTranslation#20]
Hello! This is AnyaByakuya from SF! I actually finished the Hoshidan path a month ago but have been busy to have time to post it until now. This run with the 3rd personality had more errors then for Nohr it seems

- ch 9 - Hinata refers to her as lord when recruiting
- ch 10 - when Takumi appears Sakura excitedly shouts Ryouma's name instead
- ch 12 - Elise shouts for her "brothers" to stop fighting outside
- ch 12 - this one is weird - when Takumi and the avatar are talking near the lake a blank text box shows up for her, but when you press A to go to the next prompt words fill into the blank one before [moving on](http://imgur.com/a/0uG13)
- ch 14 - Ryouma explains his silbings to Crimson as if the avatar is male, the gist of it being my younger brother Kamui, my next brother Takumi and my sisters..
- ch 15 - Suzukaze refers to her as male during the first half of the chapter/prebattle - not an issue after
- ch 16 - Felicia and Flora refer to her as male whenever adressed during Takumi's recovery scene at the end
- ch 17 - when fighting Joker, Flora's second to last text box is auto skipped to the final one
- ch 18 - at the end when Leon leaves the scene and its Kamui's turn to talk her entire convo is auto skipped and goes straight to the save screen
- ch 22 - Asura's final textbox is auto skipped right before leading them to the underground capital - this happens with Casita at the end scene as well
- ch 23 - Harold's prebattle speech has two words that need spacing
- ch 25 - when Leon tells his retainers to come out of hiding the scene fades out right into the loading screen - their entire conversation is missing
- ch 26 - Elise should have said the avatars name "Big Brother Marx! Big Sis...!" before jumping to Marx and the avatars fight - it was said for a male run
- ch 26 - this one is a dozy. At the end when the battle is over and Marx is talking with the avatar... the scene goes wonky and the [Hooded Man shows up!](http://imgur.com/a/OveZ9) and he stays there in the corner throughout the entire scene!
- endgame - Saizou has bad spacing in his motivation quote - Suzukaze refers to her as male in his
- endgame - Cyrus' input at the epilogue is auto skipped entirely

**Comment by ShadySheikah** [comment]
I think we've been able to fix almost all the errors mentioned. I'll go through and make sure we hit everything before closing the issue, though.

**Comment by ShadySheikah** [comment]
## Fixed
- Ch 9 -- Conditional wording added
- Ch 10 -- Kamui and Sakura dialogue tweaked
- Ch 12 -- Fixed a line-break error 
- Ch 14 -- Changed wording
- Ch 15 -- Changed wording
- Ch 16 -- Changed wording
- Ch 18 -- Conversation dialogue significantly reduced to meet hard-coded character limit
- Ch 22 -- Same issue as above; dialogue text significantly reduced in both cases
- Ch 23 -- Spacing added
- Ch 26 -- Hooded man no longer appears (code issue for third personality only), and wording fixed
- Endgame -- Text reduced to meet character limit, wording changed

## Not fixed
- Ch 17 -- We actually couldn't find an issue with the text or its surrounding code. We cleaned up the text a bit while we were there, though. If you happen to catch this bug again, please leave a comment here.
- Ch 25 -- As with Ch 17, we couldn't find anything wrong with the text, code, or character limit. We'll stay on the lookout for the issue, though.
