### ISSUE TITLE
Invisible Kingdom not translated for me

### ISSUE THREAD

**Issue by RikuKawai** [TeamIf/FireEmblemIf-FanTranslation#22]
I followed the directions and used the absolute newest version of the patch (used latest commits not latest release) but my Invisible Kingdom chapters are still in Japanese. Is there an extra step that was not mentioned in the instructions that I missed to patch Invisible Kingdom?

**Comment by ShadySheikah** [comment]
Thanks for reaching out. We looked through the instructions again and we couldn't find any missing steps. We're trying to figure this out, but we'll need some more information about the steps you took.

To start, were there any issues during the rebuilding process? In particular, were the romfs.bin files used created using the romfs folders with the patched content? The romfs folders will need to be packaged into romfs.bin files that replace the originals.

Also, just in case, what version of the game do you have (Hoshido, Nohr, Special, eShop)? Thanks again.

**Comment by RikuKawai** [comment]
Never mind, it was an issue on my end. I fixed it by removing the DLC, reinstalling it, and then updating all my locale entries due to the change in folder structure in newer Luma versions. Invisible Kingdom is in English now.

But for additional details I'm not using any sort of romfs.bin, I'm using the patcher to build a CIA from a dumped ROM and installing it with DevMenu. My copy of the game is the Special Edition.

**Comment by ShadySheikah** [comment]
Glad you were able to get it working! Enjoy Invisible Kingdom 😉
