### ISSUE TITLE
Patcher v4.2 "Cannot find a part of the path"

### ISSUE THREAD

**Issue by cuddletrousers** [TeamIf/FireEmblemIf-FanTranslation#24]
Redirected from SerenesForest Forums:

 Hi guys, my patcher doesn't seem to want to really work.

The first image is as far as I get, before the 2nd image gives me an error message.  I ran the program as administrator with the same result.

I am running Windows 10 64 bit Education Edition, with a 4GHz 8-core processor, 16 GB RAM, and a Radeon R9 290x graphics card.

What am I missing here?  I'll gladly post any more information you may need.

Thanks! 

![1](https://user-images.githubusercontent.com/29714404/27554807-b3e5b176-5a7d-11e7-8bff-af83e949ce0c.PNG)
![2](https://user-images.githubusercontent.com/29714404/27554809-b4f5e6e4-5a7d-11e7-985a-1480d2b86716.PNG)

**Comment by NoizeBombHD** [comment]
Having the same issue here at the moment with my patcher

**Comment by cuddletrousers** [comment]
This issue was resolved thanks to Kyonko802.  Suggested to double check if my .cia's were encrypted.  Surprise!  They were.  Sheikah can mark this as resolved.  GodMode9 took the encryption right off and problem was fixed.

![5](https://user-images.githubusercontent.com/29714404/27563625-cb608b64-5aa0-11e7-9ae8-34dc7d48ac52.PNG)

**Comment by ShadySheikah** [comment]
Awesome! I'm glad things were able to get resolved on their own.

The patcher was supposed to throw a specific error if it detected the game wasn't decrypted, but it seems the check I put in place actually caused this error instead. I'll make sure to fix that and upload a newer version for others who might come across this issue as well.
