### ISSUE TITLE
Supports issues : Zero x Belka (B) - Kamui ♀  x Joker (A)

### ISSUE THREAD

**Issue by Shanath** [TeamIf/FireEmblemIf-FanTranslation#25]
Ohayô

I noticed these 2 issues during the support conversations : 

- Support B Zero x Belka  => conversation is entirely skipped
- Support A Kamui ♀ x Joker => lines of dialogue overlap each other 

Thank you very much for all your works !

**Comment by ShadySheikah** [comment]
Both issues have been fixed/tested and will be in the next commit.
