### ISSUE TITLE
Nohr: Chapter 8 Maiden of Ice minor issue: text going out of bounds(one word only)

### ISSUE THREAD

**Issue by TsundereGuyAznMan** [TeamIf/FireEmblemIf-FanTranslation#26]
MID_B008_BT6 (use this to search for the dialogue on notepad ++)

I notice this problem when I was going pass this chapter to test some mods.   The word "opponent" goes out of bounds a little.  Fight dialogue happens between Felicia and Flora.  

Felicia: Were you planning on rebelling without\nhearing a single word from your opponent?(<--out of bounds a little)
(After a few lines)......

Flora: Even if you are my opponent,\nI will show no mercy.$k

I think the word "sister" would be better use here than "opponent" . That's it. Here is a video of the changes [before](https://drive.google.com/open?id=0B2iid5C4H16wbFNabU1iNHpvaFU) and [after](https://drive.google.com/open?id=0B2iid5C4H16wMUtZTGhSRDNRVE0).

**Comment by ShadySheikah** [comment]
Thanks for the heads up! Fixed lines will be in the next monthly commit.
