### ISSUE TITLE
Harold x Mozume, Xander x Charlotte

### ISSUE THREAD

**Issue by ShadySheikah** [TeamIf/FireEmblemIf-FanTranslation#27]
[From Elleryan on SF](https://serenesforest.net/forums/index.php?/topic/67613-fire-emblem-if-fan-translation-under-new-management/&do=findComment&comment=4926919):

> Second, i've found some issues with the latest release, i'm missing Harold x Mozume Supports (They're still in JP), The S support for Xander and Charlotte is missing too, it skips it and jumps right to the "Xander and Charlotte have reached S support".

**Comment by ShadySheikah** [comment]
Harold x Mozume was accidentally skipped by the patch assembler; fixed now.

We couldn't find anything wrong in Marx x Charlotte that could be causing an issue, so I re-inserted the English over a copy of the Japanese version of the S rank. If there was a problem in the code, it's gone now. Will test tomorrow and re-open if the problem persists.

**Comment by MissingNerd** [comment]
Why did you ship Marx and Charlotte?
