### ISSUE TITLE
[Query] Is there a sister project for the EN release?

### ISSUE THREAD

**Issue by Deadened** [TeamIf/FireEmblemIf-FanTranslation#29]
Self-explanatory.

**Comment by ShadySheikah** [comment]
Apologies for the very, very delayed response.
There isn't a sister project specifically for the EN release. However, using the patcher app that's included with our release downloads, you should have no problem using this translation with an American or European version of the game too. However, you won't be able to enable the missing Skinship mode that the JP versions have.
