### ISSUE TITLE
So uh, its dead right?

### ISSUE THREAD

**Issue by Bitwolfies** [TeamIf/FireEmblemIf-FanTranslation#33]
4 years without a single commit, sad to see it go.

**Comment by pPkMnh4to8994h** [comment]
I'm also interested in the outcome.

**Comment by PapaTurk** [comment]
Makes me wonder what this lazy fuck is doing, just creating a project and abandoning it without notice.

**Comment by MissingNerd** [comment]
> Makes me wonder what this lazy fuck is doing, just creating a project and abandoning it without notice.

Jeez dude. Relax. It's not like you paid for the fan translation.

**Comment by ShadySheikah** [comment]
A huge apology for the long absence. It wasn't intended and certainly not for as long as it was.
We're back and ready to keep pushing out updates, so please keep an eye out for more to come, and thank you for sticking with us for so long.

For more information on what's been going on, please see my post on Serenes Forest:
https://forums.serenesforest.net/index.php?/topic/67613-fire-emblem-if-fan-translation-still-alive/page/11/#comment-6031413
