### ISSUE TITLE
What going on with the patch?

### ISSUE THREAD

**Issue by PapaTurk** [TeamIf/FireEmblemIf-FanTranslation#34]
Whats taking that lazy fuck so long. We havent heard anything from him.

He can't just honestly start something and then abandon it.

Wont even give us a message.

**Comment by Elionna** [comment]
In the 3 years since the lack of an update you could have learned Japanese and played the game with the original script instead of getting mad at people working on a free mod. Only lazy person here is you.

**Comment by pPkMnh4to8994h** [comment]
And there will be no message - it seems the development is long abandoned. The official thread at Serenes Forest was closed long ago, and new threads about the fate (heh) of this translation are met with silence.
They do say that hope dies last, but, well...

**Comment by ShadySheikah** [comment]
Please keep up the hope! 
We're so sorry it took so long, but we're doing our best to get things back up and running as much as we can. We just pushed out a new update earlier today, and we hope you'll give it a try. And of course, if you find any issues or have any questions, you can always open another issue report here.

For more information on what's been going on, please see my post on Serenes Forest:
https://forums.serenesforest.net/index.php?/topic/67613-fire-emblem-if-fan-translation-still-alive/page/11/#comment-6031413
