### ISSUE TITLE
Where the hell is that lazy fuck?

### ISSUE THREAD

**Issue by Bombogor** [TeamIf/FireEmblemIf-FanTranslation#36]
Why the hell is this site still there when the creator abandoned it without any notice? Is he dead o something or is he just lazy but has not the balls to admit it?

**Comment by pPkMnh4to8994h** [comment]
Why would you post this from a new account lmao, it's painfully obvious
The thing is dead. It's still there bc devs thought they would eventually come around and finish it, but they kinda burned out. If you really do want answers - stop bitching, head to forums.serenesforest.net, and ask there, although it's unlikely that someone will respond.
No one really plays Fates anyway.

**Comment by KRSMunjiru** [comment]
> No one really plays Fates anyway.

I do. Fire Emblem Fates is my favorite game of all time and I'd like to experience it through the vision of its initial team without a toned-down localization. I still play this game, I made my friends try this game out and I am also fucking tired of people slandering it for no valid reason. If they finish the translation, GOOD. If they do not, it's unfortunate not only for me but all people who still enjoy and play this game up to now. We exist.

**Comment by Elionna** [comment]
>We exist.

A lot of you do, Fates is the best selling title second only to Three Houses. Doesn't matter what a tiny forum says about the game, it was a huge success and vast majority of people loved it. Not a surprise many people are playing it even now. Unfortunate it never got a proper localization though.

**Comment by pPkMnh4to8994h** [comment]
#39
