### ISSUE TITLE
Is the project still ongoing?

### ISSUE THREAD

**Issue by Shirokaze003** [TeamIf/FireEmblemIf-FanTranslation#37]
I'm just leaving this here for anyone who is still keeping up with this. I know the project is dead at this point, but is there still interest in it? If the devs see this, is it because of a lack of time, or something else? If it's something like a lack of funding, or a lack of interest, I'm sure we could put this out on social media, and see if we could get a gofundme going for the project. Idk. I've just really wanted an uncensored full translation of Fates since my first playthrough, and it kinda sucks that the most comprehensive one is incomplete.

**Comment by ShadySheikah** [comment]
Thanks for reaching out, and apologies for the way-too-long delay.
We did burn out initially, unfortunately. We'd tell ourselves that we'd get things going again, but that steam just didn't come back for a long time.

Luckily, we've managed to get a few of us back together and we're pushing forward with new content. Today, we put out our first update in almost five years. For more information on it, please see my post on the Serenes Forest forum:
https://forums.serenesforest.net/index.php?/topic/67613-fire-emblem-if-fan-translation-still-alive/page/11/#comment-6031413

If you have any issues with the patch or have any more questions, please feel free to open another issue here. Thank you for sticking with us for so long!
