### ISSUE TITLE
I still believe.

### ISSUE THREAD

**Issue by Soulsilvertano** [TeamIf/FireEmblemIf-FanTranslation#38]
Hello, I’m new to this whole thing and am preparing to home brew my 3DS, I’ve begun to fall in love with fates and hoping that someday you and your team can complete the project.

Shadysheikah, I’m hoping you can at least talk to us soon, I believe in you and the rest of your team, I do not care about waiting, and no news would disappoint me, I hope you’re remaining safe, take care and please make an update soon.

**Comment by pPkMnh4to8994h** [comment]
Check this to know more
#39

**Comment by ShadySheikah** [comment]
Apologies for the long absence, and thank you for the kind words! We've just released a new update to the patch earlier today, and we hope you'll give it a try. As always, it's a work-in-progress, and if you find anything odd or have any other issues with it, please feel free to open an issue report here!

And thank you for sticking with us for so long. We'll do our best to keep delivering updates on a slow-but-steady basis from now on, and we hope you'll look forward to what we have to offer.

Please see my forum post on Serenes Forest for more information on what's been going on:
https://forums.serenesforest.net/index.php?/topic/67613-fire-emblem-if-fan-translation-still-alive/page/11/#comment-6031413
