### ISSUE TITLE
"Applying patch using the provided patcher" link in README is broken

### ISSUE THREAD

**Issue by dewey5** [TeamIf/FireEmblemIf-FanTranslation#41]
The link just redirects to the ReadME page. Since the "Using the provided patcher" link is outdated, I am not sure how to actually apply the patch

**Comment by ShadySheikah** [comment]
Apologies, it should be working now. The original guide was for our older patcher program, which we don't bundle with releases anymore. I just rewrote the guide for our new patcher, and the link should be working again.

To save you time, you can find the guide here:
https://github.com/TeamIf/FireEmblemIf-FanTranslation/wiki/Using-the-Provided-Patcher

Please let me know if you have any more issues with the patching process!
