### ISSUE TITLE
erorr message when trying to patch game

### ISSUE THREAD

**Issue by p3rs0nn** [TeamIf/FireEmblemIf-FanTranslation#44]
I'm kind of new to patching games, I followed the directions on the guide and I got this error after it asked me to save the rebuilt cia, then the patcher just got stuck. I'm not sure where else to ask about this and I don't know what went wrong
<img width="320" alt="Screenshot 2023-07-31 23010345" src="https://github.com/TeamIf/FireEmblemIf-FanTranslation/assets/141103760/304eb18d-6353-4054-97b6-16592b345e6e">

**Comment by shibopanda** [comment]
Were you able to resolve this ?
