### ISSUE TITLE
Chapter 6 - Invisible Kingdom and Pieri 

### ISSUE THREAD

**Issue by otomefan** [TeamIf/FireEmblemIf-FanTranslation#5]
Something I noticed when siding with neither as female Kamui in chapter 6. Ryouma in one of the beginning dialogues says "I won't let you take him!" and when the scene cuts to Femui and Aqua she makes a male grunt sound instead of the assigned female one, example being mvoice1 instead of fvoice1.

Another thing I noticed, although not pertaining to the chapter but rather a my castle line, is when you invite Pieri over one of her lines remain untranslated, the one where she mentions her killing you if you're not doing it right. Her A support with Felicia also closes immediately upon clicking it.

**Comment by ShadySheikah** [comment]
- IK Chapter 6 gender issues fixed
- Pieri's bad touch line has been translated/edited
- Galaxygamr98 found and corrected the issue in Pieri x Felicia

Changes will be present in 4.1.
